# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0002_author_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='Life is good.'),
            preserve_default=False,
        ),
    ]
